@SETLOCAL
@CHCP 65001 >NUL:
@CD /D "%~dp0"
@IF ERRORLEVEL 1 GOTO :exit
@CALL "%~dp0\00_config.bat"
@IF ERRORLEVEL 1 GOTO :exit

@ECHO.LBHOME=%LBHOME%
@ECHO.LBPROGRAMS=%LBPROGRAMS%
@ECHO.ROOT_LB=%ROOT_LB%
@ECHO.
@SET ROOT | more

@:: Pause if not interactive
@:exit
@SET ERR=%ERRORLEVEL%
@IF ERRORLEVEL 1 @ECHO Failure ERRORLEVEL=%ERRORLEVEL%
@TYPE NUL>NUL
@ECHO %cmdcmdline% | FIND /i "%~0" >NUL
@IF NOT ERRORLEVEL 1 PAUSE
@ENDLOCAL&EXIT /B %ERR%
